project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('zap_app.urls', namespace='zap'))
]

zap_app/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as lr
from django.contrib.auth import views as auth_views

from .views import IndexView, UserRegisterView, UserProfileView, MessageCreateView, MessageListView
from .api_views import ApiMessageListView, ApiSubscribeView, ApiUnsubscribeView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),

    # User and auth
    url(r'^login/$', auth_views.login, name='user_login', kwargs={'template_name': 'zap_app/user_login.html'}),
    url(r'^register/$', UserRegisterView.as_view(), name='user_register'),
    url(r'^profile/$', lr(UserProfileView.as_view()), name='user_profile'),
    url(r'^logout/$', auth_views.logout, name='user_logout', kwargs={'template_name': 'zap_app/user_logout.html'}),

    # Messages
    url(r'^messages/$', MessageListView.as_view(), name='message_index'),
    url(r'^messages/new$', MessageCreateView.as_view(), name='message_create'),

    # API
    # Subscription (REST hooks)
    url(r'^api/v1/subscribe/$', ApiSubscribeView.as_view(), name='api_subscribe'),
    url(r'^api/v1/unsubscribe/$', ApiUnsubscribeView.as_view(), name='api_unsubscribe'),
    # Poll calls
    url(r'^api/v1/messages/$', ApiMessageListView.as_view(), name='api_message_index'),
]

zap_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from random import choice
import string


def generate_api_key():
    return ''.join([choice(string.digits + string.ascii_letters) for _ in range(32)])


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('You should enter user\' email')

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password):
        if not email:
            raise ValueError('You should enter user\' email')

        user = self.model(email=self.normalize_email(email), is_superuser=True, is_staff=True)
        user.set_password(password)
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'email'

    objects = UserManager()

    email = models.EmailField('email', unique=True)

    registered = models.DateTimeField(default=timezone.now)
    is_staff = models.BooleanField('staff status', default=False,
                                   help_text='Designates whether the user can log into this admin site.')
    is_active = models.BooleanField('активен', default=True,
                                    help_text='Designates whether this user should be treated as '
                                              'active. Unselect this instead of deleting accounts.')

    api_key = models.CharField(max_length=32, default=generate_api_key)

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email


class MessageManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('-created')


class Message(models.Model):
    text = models.TextField()
    created = models.DateTimeField(default=timezone.now)

    objects = MessageManager()


class Subscription(models.Model):
    user = models.ForeignKey(User, db_index=True)
    event = models.CharField(max_length=64)
    url = models.CharField(max_length=128, unique=True)

zap_app/forms.py
from django import forms
from django.contrib.auth import password_validation

from .models import User


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given email and password.
    """
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput,
                                help_text="Enter the same password as before, for verification.")

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.instance.email = self.cleaned_data.get('email')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
        return user

zap_app/views.py
from django.views.generic import View, TemplateView, FormView, CreateView, ListView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import login, authenticate

from .forms import UserCreationForm
from .models import Message


class IndexView(TemplateView):
    template_name = 'zap_app/index.html'

    def get_context_data(self, **kwargs):
        return {}


class UserProfileView(TemplateView):
    template_name = 'zap_app/user_profile.html'

    def get_context_data(self, **kwargs):
        return {}


class UserRegisterView(FormView):
    form_class = UserCreationForm
    template_name = 'zap_app/user_register.html'
    success_url = reverse_lazy('zap:user_profile')

    def form_valid(self, form):
        form.save()

        # Login a user right after registration
        user = authenticate(email=form.instance.email, password=form.cleaned_data["password1"])
        if user is not None:
            login(self.request, user)

        return super().form_valid(form)


class MessageListView(ListView):
    model = Message


class MessageCreateView(CreateView):
    model = Message
    fields = ('text', )
    success_url = reverse_lazy('zap:message_index')

templates/layout.html
<!doctype html>
{% load static %}
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'css/normalize.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    </head>
    <body>
        <div class="container">
            {% include 'zap_app/_menu.html' %}
            {% block content %}{% endblock %}
        </div>

        {% block extrabody %}{% endblock %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/zap_app/_menu.html
<ul>
    <li><a href="{% url 'zap:index' %}">Index</a></li>
    {% if request.user.is_authenticated %}
        <li><a href="{% url 'zap:user_profile' %}">Your profile ({{ request.user.email }})</a></li>
        <li><a href="{% url 'zap:user_logout' %}">Log out</a></li>
    {% else %}
        <li><a href="{% url 'zap:user_login' %}">Log in</a></li>
        <li><a href="{% url 'zap:user_register' %}">Register</a></li>
    {% endif %}
    <li><a href="{% url 'zap:message_index' %}">Messages</a></li>
    <li><a href="{% url 'zap:message_create' %}">Create a message</a></li>
</ul>

templates/zap_app/index.html
{% extends 'layout.html' %}
{% block title %}Index{% endblock %}

{% block content %}
    <p>Feel free to register or log in!</p>
{% endblock %}

templates/zap_app/message_form.html
{% extends 'layout.html' %}
{% block title %}Create a message{% endblock %}

{% block content %}
    <form method="post" action="{% url 'zap:message_create' %}">
        {% csrf_token %}
        <div>{{ form.text.label_tag }}</div>
        <div>{{ form.text }}</div>
        <div>{{ form.text.errors }}</div>
        <div><input type="submit" value="Submit" /></div>
    </form>
{% endblock %}

templates/zap_app/message_list.html
{% extends 'layout.html' %}
{% block title %}Messages{% endblock %}

{% block content %}
    {% for object in object_list %}
        <p>{{ object.text }}</p>
    {% endfor %}
{% endblock %}

templates/zap_app/user_login.html
{% extends 'layout.html' %}
{% block title %}Log in{% endblock %}

{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'zap:user_login' %}">
        {% csrf_token %}
        <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
        </table>

        <input type="submit" value="Log in" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}

templates/zap_app/user_logout.html
{% extends 'layout.html' %}
{% block title %}Log out{% endblock %}

{% block content %}
    <p>You were logged out. Have a nice day!</p>
{% endblock %}

templates/zap_app/user_profile.html
{% extends 'layout.html' %}
{% block title %}Log out{% endblock %}

{% block content %}
    <p>Your email is <b>{{ request.user.email }}</b></p>
    <p>Provide the data below to Zapier!</p>
    <p>
        <b>ID</b>: {{ request.user.pk }} <br>
        <b>API key</b>: {{ request.user.api_key }}
    </p>
{% endblock %}

templates/zap_app/user_register.html
{% extends 'layout.html' %}
{% block title %}Register{% endblock %}

{% block content %}
    {% if form.errors %}
        <p>Check the errors below, please.</p>
    {% endif %}

    <form method="post" action="{% url 'zap:user_register' %}">
        {% csrf_token %}
        <table>
        <tr>
            <td>{{ form.email.label_tag }}</td>
            <td>{{ form.email }}</td>
            <td>{{ form.email.errors }}</td>
        </tr>
        <tr>
            <td>{{ form.password1.label_tag }}</td>
            <td>{{ form.password1 }}</td>
            <td>{{ form.password1.errors }}</td>
        </tr>
        <tr>
            <td>{{ form.password2.label_tag }}</td>
            <td>{{ form.password2 }}</td>
            <td>{{ form.password2.errors }}</td>
        </tr>
        </table>

        <input type="submit" value="Register" />
    </form>
{% endblock %}